version: '3'

services:
  app:
    build: .
    user: node
    working_dir: /home/node/app
    entrypoint: ["sh", "-c", "npm install && tail -f /dev/null"]
    volumes:
      - .:/home/node/app